### ISSUE TITLE
Invalid memory address or nil pointer dereference.

### ISSUE THREAD

**Issue by DeveloperHZH** [hr3lxphr6j/bililive-go#32]
环境Debian10 + ffmpeg version 4.1.3-1
日志：
```
Jul 21 19:00:01 HostHatch bililive-go[27458]: time="2019-07-21 19:00:01" level=info msg="Listener Close" host_name="闻香识" id=45490ee6ba7091b04c21d463029264a0 room_name="究极钻石守门员" status=false url="https://www.huya.com/290429"
Jul 21 19:00:02 HostHatch bililive-go[27458]: time="2019-07-21 19:00:02" level=info msg="Listener Start" host_name="闻香识" id=45490ee6ba7091b04c21d463029264a0 room_name="究极钻石守门员" status=false url="https://www.huya.com/290429"
Jul 21 19:58:18 HostHatch bililive-go[27458]: time="2019-07-21 19:58:18" level=info msg="Live Start" host_name="闻香识" id=45490ee6ba7091b04c21d463029264a0 room_name="钻石艰难上分中，猎杀者冲冲冲！" status=true url="https://www.huya.com/290429"
Jul 21 19:58:18 HostHatch bililive-go[27458]: time="2019-07-21 19:58:18" level=info msg="Recorde Start" host_name="闻香识" id=45490ee6ba7091b04c21d463029264a0 room_name="钻石艰难上分中，猎杀者冲冲冲！" status=true url="https://www.huya.com/290429"
Jul 21 20:00:01 HostHatch bililive-go[27458]: time="2019-07-21 20:00:01" level=info msg="Listener Close" host_name="闻香识" id=45490ee6ba7091b04c21d463029264a0 room_name="钻石艰难上分中，猎杀者冲冲冲！" status=true url="https://www.huya.com/290429"
Jul 21 20:00:01 HostHatch bililive-go[27458]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 21 20:00:01 HostHatch bililive-go[27458]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8f62b4]
Jul 21 20:00:01 HostHatch bililive-go[27458]: goroutine 132592 [running]:
Jul 21 20:00:01 HostHatch bililive-go[27458]: github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close.func1()
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:96 +0x44
Jul 21 20:00:01 HostHatch bililive-go[27458]: sync.(*Once).Do(0xc000306fa0, 0xc0001f0f18)
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /usr/local/Cellar/go/1.12.6/libexec/src/sync/once.go:44 +0xb3
Jul 21 20:00:01 HostHatch bililive-go[27458]: github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close(0xc000104bd0)
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:94 +0x52
Jul 21 20:00:01 HostHatch bililive-go[27458]: github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).RemoveRecorder(0xc00010cee0, 0xb53c40, 0xc000126c30, 0xc000029fa0, 0x20, 0x0, 0x0)
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:94 +0xb2
Jul 21 20:00:01 HostHatch bililive-go[27458]: github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).Start.func3(0xc0003fb760)
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:54 +0xad
Jul 21 20:00:01 HostHatch bililive-go[27458]: created by github.com/hr3lxphr6j/bililive-go/src/lib/events.(*EventDispatcher).DispatchEvent
Jul 21 20:00:01 HostHatch bililive-go[27458]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/lib/events/event_dispatcher.go:56 +0xd4
Jul 21 20:00:01 HostHatch systemd[1]: bililive-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 20:00:01 HostHatch systemd[1]: bililive-go.service: Failed with result 'exit-code'.
Jul 21 20:00:01 HostHatch systemd[1]: bililive-go.service: Service RestartSec=100ms expired, scheduling restart.
Jul 21 20:00:01 HostHatch systemd[1]: bililive-go.service: Scheduled restart job, restart counter is at 2.
Jul 21 20:00:01 HostHatch systemd[1]: Stopped Live Stream Saver.
Jul 21 20:00:01 HostHatch systemd[1]: Started Live Stream Saver.
Jul 21 20:00:01 HostHatch bililive-go[25782]: time="2019-07-21 20:00:01" level=info msg="BiliLive-go Version: 0.3.7 Link Start"
Jul 21 20:00:01 HostHatch bililive-go[25782]: time="2019-07-21 20:00:01" level=info msg="Server start at 127.0.0.1:6161"
Jul 21 20:00:01 HostHatch bililive-go[25782]: time="2019-07-21 20:00:01" level=info msg="ListenerManager Start"
Jul 21 20:00:01 HostHatch bililive-go[25782]: time="2019-07-21 20:00:01" level=info msg="RecorderManager Start"
```

**Comment by hr3lxphr6j** [comment]
Duplicate of #17
