### ISSUE TITLE
斗鱼录制 报错

### ISSUE THREAD

**Issue by ghoslin01** [hr3lxphr6j/bililive-go#33]
`$ bililive-go.exe -i https://www.douyu.com/60066
time="2019-07-30 14:57:50" level=info msg="BiliLive-go Version:  Link Start"
time="2019-07-30 14:57:52" level=info msg="ListenerManager Start"
time="2019-07-30 14:57:52" level=info msg="RecorderManager Start"
time="2019-07-30 14:57:52" level=info msg="Listener Start" host_name="少囧丶" id                                                                                                                                                                                               =a3e3cb6fa20bf279b168b85887701267 room_name="下午3把鸡" status=true url="https:/                                                                                                                                                                                               /www.douyu.com/60066"
time="2019-07-30 14:57:52" level=info msg="Live Start" host_name="少囧丶" id=a3e                                                                                                                                                                                               3cb6fa20bf279b168b85887701267 room_name="下午3把鸡" status=true url="https://www                                                                                                                                                                                               .douyu.com/60066"
time="2019-07-30 14:57:52" level=info msg="Recorde Start" host_name="少囧丶" id=                                                                                                                                                                                               a3e3cb6fa20bf279b168b85887701267 room_name="下午3把鸡" status=true url="https://                                                                                                                                                                                               www.douyu.com/60066"
panic: runtime error: index out of range

goroutine 16 [running]:
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc00016846                                                                                                                                                                                               0, 0x0, 0x8, 0x0)
        C:/Users/trace/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_li                                                                                                                                                                                               ve.go:181 +0x1244
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc00016846                                                                                                                                                                                               0, 0xc00013fec0, 0x444b00, 0xc0001ec410, 0x0, 0x0)
        C:/Users/trace/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_li                                                                                                                                                                                               ve.go:239 +0x5b
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc000167570)
        C:/Users/trace/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/re                                                                                                                                                                                               corder.go:56 +0x7b
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.fun                                                                                                                                                                                               c1
        C:/Users/trace/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/re                                                                                                                                                                                               corder.go:86 +0x4e
`

**Comment by ghoslin01** [comment]
版本为
BiliLive-go Version: 0.3.8-1-g05e61f3

**Comment by ghoslin01** [comment]
比较奇怪的一个事情 我在ubuntu底下运行报上面的错 在windows底下debug 竟然录制成功了

**Comment by ghoslin01** [comment]
应该是我的编译的姿势不对...
