### ISSUE TITLE
0.7.0 启动直接 panic

### ISSUE THREAD

**Issue by cxumol** [hr3lxphr6j/bililive-go#331]
```
./bililive-go -i "https://www.douyu.com/13245" -o . --debug --native-flv-parser --interval=10 --split-strategies=on_room_name_changed
```

```
time="2023-01-13 10:32:24" level=info msg="BiliLive-go Version: v0.7.0 Link Start"
time="2023-01-13 10:32:24" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.0 BuildTime:2023-01-13_14:58:07 GitHash:18c21d4dafacc05e38f063e90b5e18cf93926c42 Pid:11087 Platform:linux/amd64 GoVersion:go1.19.4}"
time="2023-01-13 10:32:24" level=debug msg="&{File: RPC:{Enable:false Bind::8080} Debug:true Interval:10 OutPutPath:. Feature:{UseNativeFlvParser:true} LiveRooms:[{Url:https://www.douyu.com/12345 IsListening:true LiveId:}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:true MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:0 liveRoomIndexCache:map[]}"
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hr3lxphr6j/bililive-go/src/configs.(*Config).RefreshLiveRoomIndexCache(...)
        /home/runner/work/bililive-go/bililive-go/src/configs/config.go:154
github.com/hr3lxphr6j/bililive-go/src/configs.(*Config).GetLiveRoomByUrl(0xc0000ba6e0, {0xc00036a090, 0x1c})
        /home/runner/work/bililive-go/bililive-go/src/configs/config.go:173 +0x40b
main.main()
        /home/runner/work/bililive-go/bililive-go/src/cmd/bililive/bililive.go:115 +0xa88
```

回退 0.6.8 正常 感觉像是 liveRoomIndexCache 引起的

**Comment by kira1928** [comment]
哭了T_T
我修。。

**Comment by kira1928** [comment]
0.7.1 绝赞打包中 https://github.com/hr3lxphr6j/bililive-go/actions/runs/3912989860
我太困了，先睡了。还有问题的话明天修T_T

**Comment by kira1928** [comment]
于0.7.1中修复
