### ISSUE TITLE
win平台端有2个问题

### ISSUE THREAD

**Issue by JaydenFish** [hr3lxphr6j/bililive-go#72]
1.保存配置的时候，config.yml会被保存成只读文件，下一次就无法保存了
2.连续运行2天多，会自动退出。

**Comment by hr3lxphr6j** [comment]
第二个问题麻烦提供下日志

**Comment by JaydenFish** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4566c8]

goroutine 243 [running]:
time.stopTimer(0xc0003f9d68, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/time.go:224 +0x32
time.(*Timer).Stop(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/time/sleep.go:78
net/http.(*http2ClientConn).roundTrip(0xc001bf9e00, 0xc001956800, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:7480 +0xa6
net/http.(*http2Transport).RoundTripOpt(0xc000080ea0, 0xc001956800, 0x9c5a00, 0xc0001ae720, 0xc0018180c0, 0x5)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6948 +0x176
net/http.(*http2Transport).RoundTrip(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6909
net/http.http2noDialH2RoundTripper.RoundTrip(0xc000080ea0, 0xc001956800, 0xcb06c0, 0xc000080ea0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:9103 +0x45
net/http.(*Transport).roundTrip(0x10a1da0, 0xc001956800, 0xc002cec410, 0x8, 0x40d83f)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/transport.go:515 +0xd9b
net/http.(*Transport).RoundTrip(0x10a1da0, 0xc001956800, 0x10a1da0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/roundtrip.go:17 +0x3c
net/http.send(0xc001956800, 0xcaf900, 0x10a1da0, 0x0, 0x0, 0x0, 0xc00019c150, 0xc000694120, 0x1, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc0000a6c60, 0xc001956800, 0x0, 0x0, 0x0, 0xc00019c150, 0x0, 0x1, 0x50d3da)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc0000a6c60, 0xc001956800, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:567
github.com/hr3lxphr6j/bililive-go/src/pkg/http.do(0xa65eaf, 0x3, 0xc0018180c0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:77 +0x4ab
github.com/hr3lxphr6j/bililive-go/src/pkg/http.Get(...)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:24
github.com/hr3lxphr6j/bililive-go/src/live/douyu.(*Live).GetInfo(0xc0004781c0, 0x2, 0x100c0028c1c60, 0x0)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/douyu/douyu.go:159 +0x13c
github.com/hr3lxphr6j/bililive-go/src/live.(*wrappedLive).GetInfo(0xc00046baa0, 0x28, 0x0, 0xc004129e48)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/lives.go:54 +0x3e
github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).refresh(0xc000474190)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:74 +0x52
github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).run(0xc000474190)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:116 +0x9f
created by github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).Start
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:61 +0x12f
```

**Comment by hr3lxphr6j** [comment]
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x4566c8]
> 
> goroutine 243 [running]:
> time.stopTimer(0xc0003f9d68, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/time.go:224 +0x32
> time.(*Timer).Stop(...)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/time/sleep.go:78
> net/http.(*http2ClientConn).roundTrip(0xc001bf9e00, 0xc001956800, 0x0, 0x0, 0x0, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:7480 +0xa6
> net/http.(*http2Transport).RoundTripOpt(0xc000080ea0, 0xc001956800, 0x9c5a00, 0xc0001ae720, 0xc0018180c0, 0x5)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6948 +0x176
> net/http.(*http2Transport).RoundTrip(...)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6909
> net/http.http2noDialH2RoundTripper.RoundTrip(0xc000080ea0, 0xc001956800, 0xcb06c0, 0xc000080ea0, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:9103 +0x45
> net/http.(*Transport).roundTrip(0x10a1da0, 0xc001956800, 0xc002cec410, 0x8, 0x40d83f)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/transport.go:515 +0xd9b
> net/http.(*Transport).RoundTrip(0x10a1da0, 0xc001956800, 0x10a1da0, 0x0, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/roundtrip.go:17 +0x3c
> net/http.send(0xc001956800, 0xcaf900, 0x10a1da0, 0x0, 0x0, 0x0, 0xc00019c150, 0xc000694120, 0x1, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:252 +0x445
> net/http.(*Client).send(0xc0000a6c60, 0xc001956800, 0x0, 0x0, 0x0, 0xc00019c150, 0x0, 0x1, 0x50d3da)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:176 +0x101
> net/http.(*Client).do(0xc0000a6c60, 0xc001956800, 0x0, 0x0, 0x0)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:699 +0x451
> net/http.(*Client).Do(...)
>         /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:567
> github.com/hr3lxphr6j/bililive-go/src/pkg/http.do(0xa65eaf, 0x3, 0xc0018180c0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:77 +0x4ab
> github.com/hr3lxphr6j/bililive-go/src/pkg/http.Get(...)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:24
> github.com/hr3lxphr6j/bililive-go/src/live/douyu.(*Live).GetInfo(0xc0004781c0, 0x2, 0x100c0028c1c60, 0x0)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/douyu/douyu.go:159 +0x13c
> github.com/hr3lxphr6j/bililive-go/src/live.(*wrappedLive).GetInfo(0xc00046baa0, 0x28, 0x0, 0xc004129e48)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/lives.go:54 +0x3e
> github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).refresh(0xc000474190)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:74 +0x52
> github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).run(0xc000474190)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:116 +0x9f
> created by github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).Start
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:61 +0x12f
> ```

这是在Windows上输出的？

**Comment by JaydenFish** [comment]
是， 在release下载的版本
App Name	BiliLive-go	App Version	0.5.2	Build Time	2020-05-20_01:24:21
Pid	37504	Platform	windows/amd64	Go Version	go1.14
Git Hash	64946304118ab375fa6ad57ab0b90b2bd0d59c7a

**Comment by JaydenFish** [comment]
0.5.3版本也崩了
```
time="2020-06-15 01:21:43" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:21:48" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:21:53" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:21:58" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:03" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:09" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:14" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:19" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:24" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:29" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:34" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:39" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:44" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:50" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:22:55" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:00" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:05" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:10" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:15" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:20" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:25" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:27" level=info msg="Live end" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:23:27" level=info msg="Record End" host="cbb丶丶" room="约菜娜bb恰饭 今日1.2倍"
time="2020-06-15 01:50:01" level=debug msg=EOF host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:01" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:06" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:11" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:16" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:22" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:27" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:32" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:37" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:42" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:47" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:52" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:50:57" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:51:03" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:51:08" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:51:12" level=info msg="Live end" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 01:51:12" level=info msg="Record End" host="豆乐乐咩" room="我的直播间，有一百万种可能"
time="2020-06-15 04:08:45" level=debug msg=EOF host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:08:45" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:08:51" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:08:56" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:01" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:06" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:11" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:16" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:21" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:26" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:32" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:37" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:42" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:47" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:52" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:09:57" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:02" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:08" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:13" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:18" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:23" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:28" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:33" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:38" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:43" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:49" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:54" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:10:59" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:04" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:09" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:14" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:19" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:24" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:30" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:35" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:40" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:45" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:50" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:11:55" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:01" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:06" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:11" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:16" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:21" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:26" level=warning msg="failed to get stream url, will retry after 5s..." error="get stream error" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:27" level=info msg="Live end" host="Zero悠然" room="总有人会为你而来 .."
time="2020-06-15 04:12:27" level=info msg="Record End" host="Zero悠然" room="总有人会为你而来 .."
panic: runtime error: racy use of timers

goroutine 111 [running]:
time.stopTimer(0xc00043c5f8, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/time.go:224 +0x32
time.(*Timer).Stop(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/time/sleep.go:78
net/http.(*http2ClientConn).roundTrip(0xc00027f080, 0xc0010dbb00, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:7480 +0xa6
net/http.(*http2Transport).RoundTripOpt(0xc000106420, 0xc0010dbb00, 0x9c5a00, 0xc00010a8d0, 0xc0032e0cf0, 0x5)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6948 +0x176
net/http.(*http2Transport).RoundTrip(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:6909
net/http.http2noDialH2RoundTripper.RoundTrip(0xc000106420, 0xc0010dbb00, 0xcb0740, 0xc000106420, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/h2_bundle.go:9103 +0x45
net/http.(*Transport).roundTrip(0x10a1e20, 0xc0010dbb00, 0xc000991c70, 0x8, 0x40d83f)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/transport.go:515 +0xd9b
net/http.(*Transport).RoundTrip(0x10a1e20, 0xc0010dbb00, 0x10a1e20, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/roundtrip.go:17 +0x3c
net/http.send(0xc0010dbb00, 0xcaf980, 0x10a1e20, 0x0, 0x0, 0x0, 0xc001892420, 0xc0034d7bc0, 0x1, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc0000a6c60, 0xc0010dbb00, 0x0, 0x0, 0x0, 0xc001892420, 0x0, 0x1, 0x50d3da)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc0000a6c60, 0xc0010dbb00, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /home/travis/.gimme/versions/go1.14.linux.amd64/src/net/http/client.go:567
github.com/hr3lxphr6j/bililive-go/src/pkg/http.do(0xa65f2f, 0x3, 0xc0032e0cf0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:77 +0x4ab
github.com/hr3lxphr6j/bililive-go/src/pkg/http.Get(...)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/pkg/http/http.go:24
github.com/hr3lxphr6j/bililive-go/src/live/douyu.(*Live).GetInfo(0xc00007fbc0, 0xa12c40, 0xc000288900, 0x9bb0a0)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/douyu/douyu.go:159 +0x13c
github.com/hr3lxphr6j/bililive-go/src/live.(*wrappedLive).GetInfo(0xc000288900, 0xc003cca100, 0x0, 0x0)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/live/lives.go:54 +0x3e
github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).refresh(0xc00043c6e0)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:74 +0x52
github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).run(0xc00043c6e0)
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:116 +0x9f
created by github.com/hr3lxphr6j/bililive-go/src/listeners.(*listener).Start
        /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/listeners/listener.go:61 +0x12f
```

**Comment by hr3lxphr6j** [comment]
https://github.com/golang/go/issues/37449
