### ISSUE TITLE
下载特定视频意外出错退出

### ISSUE THREAD

**Issue by foxyuaaalll** [hr3lxphr6j/bililive-go#779]
### 程序版本

V5.4

### 所使用的 config 文件的内容

无

### 程序 log

网络异常:
正在进行第 1 次重试
【视频】2024-08-02 18.54.29-视频-一一丫丫-还记得6年前的那两个小丫头吗？是的，她们已经长大了 #一一丫丫 #抖音潮流舞蹈地图
#不怕不怕舞蹈 下载中断，错误信息：
2024-08-02 18.54.29-视频-一一丫丫-还记得6年前的那两个小丫头吗？是的，她们已经长大了 #一一丫丫 #抖音潮流舞蹈地图
#不怕不怕舞蹈.mp4 文件已删除
Traceback (most recent call last):
  File "main.py", line 7, in main
  File "src\application\TikTokDownloader.py", line 327, in run
  File "src\application\TikTokDownloader.py", line 212, in main_menu
  File "src\application\TikTokDownloader.py", line 295, in compatible
  File "src\application\TikTokDownloader.py", line 220, in complete
  File "src\application\main_complete.py", line 1522, in run
  File "src\application\main_complete.py", line 263, in account_acquisition_interactive
  File "src\application\main_complete.py", line 281, in __account_secondary_menu
  File "src\application\main_complete.py", line 898, in __multiple_choice
  File "src\application\main_complete.py", line 351, in account_detail_inquire
  File "src\application\main_complete.py", line 389, in __account_detail_handle
  File "src\application\main_complete.py", line 460, in deal_account_detail
  File "src\application\main_complete.py", line 524, in _batch_process_detail
  File "src\application\main_complete.py", line 571, in download_account_detail
  File "src\downloader\download.py", line 123, in run
  File "src\downloader\download.py", line 151, in run_batch
  File "src\downloader\download.py", line 275, in batch_processing
  File "src\downloader\download.py", line 296, in downloader_chart
  File "src\tools\retry.py", line 17, in inner
  File "src\downloader\download.py", line 471, in request_file
  File "httpx\_models.py", line 761, in raise_for_status
httpx.HTTPStatusError: Client error '424 Failed Dependency' for url 'http://v3-web.douyinvod.com/5be71a3ba9b1f7e14b213ad124654a9f/66b0687c/video/tos/cn/tos-cn-ve-15/8ec38077027646609161efd2e83d1078/?a=6383&ch=10010&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2004&bt=2004&cs=0&ds=3&ft=khyHAB1UiiuG1_rMCdOC~49Zyo3nOz7_9r7bpMyC~_7gaXQ2B22_TWDMDoMUmbd.o~&mime_type=video_mp4&qs=0&rc=Z2c0PDxmOWQ2Njs0PDQ5N0BpM2Rod3lmc2l4dDMzOmkzM0BjLl80LzFiNi8xMzAvLWE1YSNoYmhpL2cubm9fLS1fLS9zcw%3D%3D&btag=c0000e00010000&cquery=100B_102v_102u_100o_101r&dy_q=1722826301&l=20240805105141EE30592C39E298B5E03F'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/424

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 687, in run_until_complete
  File "main.py", line 6, in main
  File "src\application\TikTokDownloader.py", line 102, in __aexit__
  File "src\application\TikTokDownloader.py", line 352, in close
  File "src\application\TikTokDownloader.py", line 330, in delete_cache
  File "shutil.py", line 781, in rmtree
  File "shutil.py", line 635, in _rmtree_unsafe
  File "shutil.py", line 633, in _rmtree_unsafe
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\Users\\110\\Desktop\\TikTokDownloader_V5.4_WIN\\_internal\\cache\\2020-04-22 21.02.00-视频-一一丫丫-有两个漏风的棉袄是种什么体验。#坑爹 @抖音小助手.mp4'
[1252] Failed to execute script 'main' due to unhandled exception!

### 自由描述

下载该主播发布视频，每次到这个视频就会报错推出，重复下载也是到这里就结束了。不知道什么情况

**Comment by foxyuaaalll** [comment]
> 你发的不是这个项目的问题 看清楚再发issues
抱歉，搞错了
怎么能关闭这个issues呢
